version: '3.8'

services:
  vibe-db:
    image: postgres:17-alpine
    container_name: vibe-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DATA_DIR:-./vibe-local-data}/postgres:/var/lib/postgresql/data
    networks:
      - vibe-network

  vibe-cache:
    image: redis:8.0-alpine
    container_name: vibe-cache
    restart: unless-stopped
    command: redis-server --appendonly yes --notify-keyspace-events Ex
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_DIR:-./vibe-local-data}/redis:/data
    networks:
      - vibe-network

  vibe-storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: vibe-storage
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ${DATA_DIR:-./vibe-local-data}/minio:/data
    networks:
      - vibe-network

networks:
  vibe-network:
    driver: bridge

#volumes:
#  pg_data:
#  redis_data:
#  minio_data: