version: '3.8'

services:
  vibe-db:
    image: postgres:17-alpine
    container_name: vibe-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: vibe_db
    ports:
      - "5432:5432"
    volumes:
      - D:/vibe-data/postgres:/var/lib/postgresql/data
    networks:
      - vibe-network

  vibe-cache:
    image: redis:8.0-alpine
    container_name: vibe-cache
    # enable keyspace notifications & append-only mode for durability
    command: redis-server --appendonly yes --notify-keyspace-events Ex
    ports:
      - "6379:6379"
    volumes:
      - D:/vibe-data/redis:/data
    networks:
      - vibe-network

  vibe-storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: vibe-storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - D:/minio/data:/data
    networks:
      - vibe-network

networks:
  vibe-network:
    driver: bridge