server:
  port: 8080
spring:
  config:
    import: "optional:file:app.env[.properties]"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vibedb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

# MinIO / S3 Configuration
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: vibe-storage
  region: us-east-1

security:
  jwt:
    secret-key: "91f6b3d88bdd0c39fa408b0ee613cdd4e83c774c9440e96c3107e1dc8604a4c8"
    issuer: "VibeApp"
    expiration-ms: 3600
    refresh-expiration-ms: 604800

node-id: "1"